import Link from "next/link";
import { ArrowRight, CheckCircle2, ChevronRight, Gauge, Layers3, Settings2, ShieldCheck } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { markets, productFamilies } from "@/data/site";

export default function Home(){return <>
<Header/>
<main>
<section className="relative overflow-hidden bg-pdc-deep text-white">
  <div className="absolute inset-0 grid-bg opacity-25"/><div className="orb right-[-8rem] top-[-10rem]"/>
  <div className="relative mx-auto grid min-h-[760px] max-w-[1440px] items-center gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-10">
    <div className="max-w-3xl">
      <p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[.22em] text-pdc-lime"><span className="h-px w-10 bg-pdc-lime"/> Engineered since 1970</p>
      <h1 className="text-5xl font-black leading-[.95] tracking-[-.055em] sm:text-7xl lg:text-[92px]">Flow control,<br/><span className="text-white/45">precisely built.</span></h1>
      <p className="mt-8 max-w-xl text-lg leading-8 text-white/68">Valves, dampers, and actuation systems configured for demanding industrial applications and built around your operating conditions.</p>
      <div className="mt-10 flex flex-wrap gap-3"><Link href="/products" className="rounded-full bg-pdc-lime px-6 py-4 font-bold text-pdc-deep">Explore Products</Link><Link href="/request-a-quote" className="rounded-full border border-white/20 px-6 py-4 font-bold">Talk to Engineering</Link></div>
    </div>
    <div className="relative mx-auto aspect-square w-full max-w-[590px]">
      <div className="absolute inset-[12%] rounded-full border border-white/10"/><div className="absolute inset-[22%] rounded-full border border-dashed border-pdc-lime/35 animate-spin-slow"/>
      <div className="absolute inset-[29%] rounded-full bg-gradient-to-br from-pdc-steel to-pdc-green shadow-2xl"><div className="absolute inset-[16%] rounded-full border-[18px] border-white/25"><div className="absolute inset-[18%] rounded-full bg-pdc-deep"/></div></div>
      <div className="tech-chip left-0 top-[20%]"><span>CASTING LIBRARY</span><strong>300+</strong></div><div className="tech-chip bottom-[15%] right-0"><span>MAX TEMPERATURE</span><strong>1500°F</strong></div>
    </div>
  </div>
</section>
<section className="border-b bg-white"><div className="mx-auto grid max-w-[1440px] grid-cols-2 lg:grid-cols-4">{[["50+","Years of engineering"],["300+","Casting patterns"],["10","Core product lines"],["ISO","9001:2015 certified"]].map(([v,l])=><div key={l} className="border-r border-pdc-deep/10 px-5 py-8 lg:px-10"><div className="text-3xl font-black text-pdc-deep">{v}</div><div className="mt-1 text-sm text-pdc-graphite/55">{l}</div></div>)}</div></section>
<section className="bg-pdc-mist px-5 py-24 lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="mb-14 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Product systems</p><h2 className="section-title">One source.<br/>Complete control.</h2></div><p className="max-w-lg text-lg leading-8 text-pdc-graphite/65">From valve body to actuator package, PDC configures complete assemblies around pressure, temperature, media, torque, and installation requirements.</p></div><div className="grid gap-4 lg:grid-cols-2">{productFamilies.map((p,i)=><Link href={p.href} key={p.title} className="group rounded-2xl border border-pdc-deep/10 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-soft lg:p-9"><div className="flex items-start justify-between"><span className="text-xs font-bold tracking-[.18em] text-pdc-green">0{i+1} / {p.eyebrow}</span><span className="grid h-10 w-10 place-items-center rounded-full border border-pdc-deep/10 transition group-hover:bg-pdc-deep group-hover:text-white"><ArrowRight size={18}/></span></div><h3 className="mt-12 text-3xl font-black tracking-tight text-pdc-deep">{p.title}</h3><p className="mt-4 max-w-xl leading-7 text-pdc-graphite/60">{p.description}</p><div className="mt-8 flex gap-8 border-t border-pdc-deep/10 pt-5"><div><strong>{p.metric}</strong><span className="block text-xs text-pdc-graphite/45">Range</span></div><div><strong>{p.sub}</strong><span className="block text-xs text-pdc-graphite/45">Capability</span></div></div></Link>)}</div></div></section>
<section className="bg-white px-5 py-24 lg:px-10"><div className="mx-auto grid max-w-[1440px] gap-16 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Engineering advantage</p><h2 className="section-title">Configured beyond the catalog.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-pdc-graphite/65">PDC combines a deep casting library, in-house machining, custom brackets, seating options, and application support to solve non-standard flow-control challenges.</p><Link href="/company/capabilities" className="mt-8 inline-flex items-center gap-2 font-bold text-pdc-green">Explore capabilities <ChevronRight size={18}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[[Gauge,"Application evaluation"],[Settings2,"In-house machining"],[Layers3,"Integrated assemblies"],[ShieldCheck,"Quality & compliance"]].map(([Icon,title])=>{const I=Icon as typeof Gauge; return <div key={String(title)} className="rounded-2xl bg-pdc-mist p-7"><I className="text-pdc-green"/><h3 className="mt-10 text-xl font-black text-pdc-deep">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-pdc-graphite/60">Engineering support from product selection through configured, installation-ready delivery.</p></div>})}</div></div></section>
<section className="bg-pdc-navy px-5 py-24 text-white lg:px-10"><div className="mx-auto max-w-[1440px]"><p className="eyebrow text-pdc-lime">Markets served</p><div className="mt-5 grid gap-2 lg:grid-cols-2">{markets.map((m,i)=><Link href={`/markets/${m.toLowerCase().replaceAll(" & ","-").replaceAll(" ","-")}`} key={m} className="group flex items-center justify-between border-b border-white/15 py-6 text-2xl font-bold sm:text-3xl"><span><small className="mr-5 text-xs text-white/35">0{i+1}</small>{m}</span><ArrowRight className="transition group-hover:translate-x-2"/></Link>)}</div></div></section>
<section className="bg-pdc-green px-5 py-20 text-white lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-10 lg:flex-row lg:items-center"><div><div className="mb-4 flex gap-3 text-sm font-bold"><CheckCircle2/> ISO 9001:2015 certified</div><h2 className="max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Bring us the operating challenge.</h2></div><Link href="/request-a-quote" className="shrink-0 rounded-full bg-white px-7 py-4 font-bold text-pdc-deep">Start a technical quote</Link></div></section>
</main><Footer/></>}
